name: Build (Linux)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install GCC
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Setup CMake 3.29.0
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '4.1.1'

      - name: Verify CMake version
        run: cmake --version

      - name: Configure
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release

      - name: Run executable
        run: ./build/src/LowLevelCppDesigns || echo "Executable not found."
