name: Windows CMake Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up MSVC environment
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '4.1.1'

      - name: Configure
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build --config Debug

      - name: Run executable
        run: .\build\src\Debug\LowLevelCppDesigns.exe
        shell: cmd

      - name: Clean up
        run: if exist build rmdir /s /q build
        shell: cmd
